let nomeCompleto = prompt('Qual seu nome completo')
const dataNascimento = Number(prompt('Qual a data do seu nascimento?'))
let endereco = prompt('Qual seu endereço?')
const cpf = Number(prompt('Qual seu CPF?'))
let escolaridade = prompt('Qual seu grau de escolaridade?')
let cnh = confirm('Você possui CNH?')
let filhos = Number(prompt('Quantos filhos você possui?'))
let cargo = prompt('Qual seu cargo atual?')
let salario = Number(prompt('Qual seu salário?'))
let comissao = prompt('Recebe comissão? Se sim, informe a porcentagem, caso não, responda com zero')
const admissao = Number(prompt('Qual ano de admissão?'))

console.log('variável nome tipo:', typeof nomeCompleto)
console.log('variável dataNascimento tipo:', typeof dataNascimento)
console.log('variável endereco tipo:', typeof endereco)
console.log('variável cpf tipo:', typeof cpf)
console.log('variável escolaridade tipo:', typeof escolaridade)
console.log('variável cnh tipo:', typeof cnh)
console.log('variável filhos tipo:', typeof filhos)
console.log('variável cargo tipo:', typeof cargo)
console.log('variável salario tipo:', typeof salario)
console.log('variável comissao tipo:', typeof comissao)
console.log('variável admissao tipo:', typeof admissao)

console.log('Nome: ', nomeCompleto)
console.log('Nascimento: ', dataNascimento)
console.log('Endereço: ', endereco)
console.log('CPF: ', cpf)
console.log('Escolaridade: ', escolaridade)
console.log('CNH: ', cnh)
console.log('Filhos: ', filhos)
console.log('Cargo: ', cargo)
console.log('Salário: ', salario)
console.log('Comissão: ', comissao)
console.log('Data Admissão: ', admissao)